<a href="https://colab.research.google.com/github/kokahonta/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensor using Tensorflow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulation tensors
* Tesnors & NumPy
* Using @tf.function(a way to speed up your regular Python function)
* Using GPUs with TensorFlow(or TPUs)
* Excercises to try yourself!

## Introduction to Tensors

In [23]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.3.0


In [3]:
# Create tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stand for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector =tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# Check the dimenstion of our vercto
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimension)
matrix =tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
# Check the dimenstion of our Matrix
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix=tf.constant([[10.,7],
                            [5.,1.],
                            [12.,5.]],dtype=tf.float16) # specify the data type with float
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5.,  1.],
       [12.,  5.]], dtype=float16)>

In [10]:
# Whats the number dimensional of another_matrix
another_matrix.ndim

2

In [11]:
# Let's create a tensor

In [12]:
tensor=tf.constant([[[1,2,3],
                     [4,5,6],
                     [8,9,10]],
                    [[11,2,12],
                     [12,32,12],
                     [123,121,1]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6],
        [  8,   9,  10]],

       [[ 11,   2,  12],
        [ 12,  32,  12],
        [123, 121,   1]]])>

In [13]:
tensor.ndim

3

What we've coreated so far:


1.   Scalar: a single number
2.   Vector: a number with direction (e.g) wind speed and direction
3. Matrix: a 2-dimensional array of numbers
4. Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector, a 2-dimensional tensor is a matrix)




### Creating tensors with `tf.variable`

In [14]:
# Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,5])
unchangebale_tensor=tf.constant([5,10])
changeable_tensor, unchangebale_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 10])>)

In [15]:
# Let's try chnage one of the elemets in our changeable tensor
changeable_tensor[0]=5
changeable_tensor

TypeError: ignored

In [16]:
# How about we try .assign()
changeable_tensor[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 5])>

In [17]:
# Let's try change our unchangeable tensor
unchangebale_tensor[0].assign(5)

AttributeError: ignored

🔑<b>Note:</b> Rarely in practice will you need to decide whether to use `t.constant` or `tf.variabl` to create tensors, as TensorFlow done this for you. However, if in doubt, use `tf.contant` and change it later if needed.

### Create random tensors

Random tensors are tensors of some abitrary size which contain random numbers
